
// This file has been generated by the GUI designer. Do not modify.
namespace MineGtkView
{
	public partial class MineWindow
	{
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget MineGtkView.MineWindow
			this.Name = "MineGtkView.MineWindow";
			this.Title = global::Mono.Unix.Catalog.GetString ("MineWindow");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 400;
			this.DefaultHeight = 300;
			this.Show ();
		}
	}
}
